# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    film_cache_dir: filmcache
    #parameter_name: value

services:
    film.repository.actor:
        class: FilmBundle\Repository\MySQLActorRepository
        public: true
        arguments:
            - "@doctrine.orm.default_entity_manager"

    film.repository.film:
        class: FilmBundle\Repository\MySQLFilmRepository
        public: true
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@film.service.cache"

    film.command.handler.create.owner:
        class: FilmApp\Application\CommandHandler\Actor\CreateActorCommandHandler
        public: true
        arguments:
            - "@film.repository.actor"

    film.command.handler.create.film:
        class: FilmApp\Application\CommandHandler\Film\CreateFilmCommandHandler
        public: true
        arguments:
            - "@film.repository.film"
            - "@film.repository.actor"

    film.command.handler.read.film:
        class: FilmApp\Application\CommandHandler\Film\ReadFilmCommandHandler
        public: true
        arguments:
            - "@film.repository.film"

    film.service.cache:
        class: FilmBundle\Service\CacheService
        arguments:
            - "%kernel.root_dir%/../var/cache/%film_cache_dir%"