# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    film.repository.actor:
        class: FilmBundle\Repository\MySQLActorRepository
        public: false
        arguments:
            - "@doctrine.orm.default_entity_manager"

    film.command.handler.create.owner:
        class: FilmApp\Application\CommandHandler\Actor\CreateActorCommandHandler
        public: true
        arguments:
            - "@film.repository.actor"