film_homepage:
    path:     /
    defaults: { _controller: FilmBundle:Default:index }

film_show:
    path: /film/{id}/
    defaults: { _controller: FilmBundle:Film:show }
    methods: [GET]
    requirements:
        param1: 'd+'

api_actor_show:
    path: /actor/{id}/
    defaults: { _controller: FilmBundle:Actor:show }
    methods: [GET]
    requirements:
        param1: 'd+'

api_actor_create:
    path: /api/actor/create/
    defaults: { _controller: FilmBundle:ApiActor:create }
    methods: [POST]

api_film_create:
    path: /api/film/create/
    defaults: { _controller: FilmBundle:ApiFilm:create }
    methods: [POST]

api_film_read:
    path: /api/film/{id}/
    defaults: { _controller: FilmBundle:ApiFilm:read }
    methods: [GET]
    requirements:
        param1: 'd+'
