FilmApp\Domain\Film:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            unique: true
        description:
            type: text
            nullable: true
    manyToOne:
        actor:
            targetEntity: Actor
            joinColumn:
                name: actor_id
                referencedColumnName: id
            fetch: EAGER
    lifecycleCallbacks: {  }
